"""create tables

Revision ID: 3e006665aa47
Revises: 
Create Date: 2022-07-03 02:36:27.855186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e006665aa47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__country')),
    sa.UniqueConstraint('label', name=op.f('uq__country__label'))
    )
    op.create_index('ix_country_label', 'country', ['label'], unique=False, postgresql_using='hash')
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw', sa.String(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('manual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name=op.f('fk__address__country_id__country'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__address'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    op.drop_index('ix_country_label', table_name='country', postgresql_using='hash')
    op.drop_table('country')
    # ### end Alembic commands ###
